### ISSUE TITLE
Descriptor loss train

### ISSUE THREAD

**Issue by ericzzj1989** [shaofengzeng/SuperPoint-Pytorch#24]
Hi, first thank you for this great work which really helped me a lot!
I want to use the Superpoint model to train on my own data. The detection loss part seems normal but the descriptor loss is oscillating and cannot converge.
The input are 256*256 image and warped image with homography, and the model and loss function are the same with your repo.
The detector and descriptor loss are as below with 300 epochs.
**Detector loss**
![image](https://user-images.githubusercontent.com/39327238/212631062-66d413e1-ac1b-4e51-ad1c-0e1d21cdfce4.png)
**Descriptor loss**
![image](https://user-images.githubusercontent.com/39327238/212630180-62e9fcd6-1e54-4d36-b7f2-6d44cef71fc5.png)

Can you give me some advice?

**Comment by shaofengzeng** [comment]
According to my experience,  these parameters 
```
solver:
    loss:
        positive_margin: 1.0
        negative_margin: 0.2
        lambda_d: 0.05
        lambda_loss: 10000
    base_lr: 0.001 #0.0001
```
, are the key parameters that affect descriptor loss, especially the `lambda_loss`.
